repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.11
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # Keep uv.lock up-to-date.
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.8
    hooks:
      - id: uv-lock

  # Prevent secrets from being committed.
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.26.0
    hooks:
      - id: gitleaks
  